apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager
    kind: SecretStore
  target:
    name: external-secret
  data:
  - secretKey: COS_CREDENTIAL
    remoteRef:
      key: iam_credentials/5118b48f-dbe8-5547-2e64-a453f6af6a94