apiVersion: v1
kind: Pod
metadata:
  name: py-example
spec:
  containers:
  - name: envars-test-container
    image: quay.io/uirlis/pysec
    env:
    - name: COS_CREDENTIAL
      valueFrom:
        secretKeyRef:
          name: external-secret
          key: COS_CREDENTIAL
    - name: COS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: appconfig
          key: COS_ENDPOINT
    - name: COS_AUTH_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: appconfig
          key: COS_AUTH_ENDPOINT
    - name: COS_SERVICE_INSTANCE_ID
      valueFrom:
        secretKeyRef:
          name: appconfig
          key: COS_SERVICE_INSTANCE_ID
